import * as cheerio from 'cheerio'
import { parseSwimTime } from '@viniswim/shared'
import type { Identifier, ParsedEntry, ParsedResult, ScanOutput, SourceAdapter } from './types.js'

const normalize=(s='')=>String(s).normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase().replace(/\s+/g,' ').trim()
const meetBase=(url:string)=>String(url).replace(/\/(athletes|results)\/?$/,'').replace(/\/$/,'')
async function get(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{headers:{'user-agent':'VINISWIM Commercial Monitor/1.0'},signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function names(i:Identifier){return [i.external_name,i.athletes?.full_name,i.athletes?.preferred_name].filter(Boolean).map(x=>normalize(String(x)))}
function athleteMatch(text:string,i:Identifier){const n=normalize(text);return n.includes(normalize(i.external_id))||names(i).some(x=>x&&n.includes(x))}
function status(text:string):ParsedResult['status']|null{const s=normalize(text);if(/\bdns\b|nao compareceu/.test(s))return'dns';if(/\bdsq\b|\bdq\b|desclassific/.test(s))return'dsq';if(/\bdnf\b|nao completou|abandonou/.test(s))return'dnf';return null}
function eventFrom(text:string){const m=text.match(/((?:\d+x)?\d{2,4})\s*m?\s+(Livre|Costas|Peito|Borboleta|Medley)/i);return m?`${m[1]} ${m[2]}`:null}
function discover(html:string,base:string){const $=cheerio.load(html);const out=new Map<string,string>();$('a[href*="?e="],a[href*="&e="]').each((_,a)=>{try{const u=new URL($(a).attr('href')||'',base);const id=u.searchParams.get('e');if(id){const p=new URL(meetBase(base)+'/results');p.searchParams.set('e',id);out.set(p.toString(),$(a).text().replace(/\s+/g,' ').trim())}}catch{}});for(const m of html.matchAll(/[?&]e=([A-Za-z0-9-]{8,})/g)){const p=new URL(meetBase(base)+'/results');p.searchParams.set('e',m[1]);if(!out.has(p.toString()))out.set(p.toString(),'')}return [...out].map(([url,label])=>({url,label}))}
function parseDate(text:string){const m=text.match(/\b(\d{2})\/(\d{2})\/(\d{4})\b/);return m?`${m[3]}-${m[2]}-${m[1]}`:null}
function parseMeet(html:string,url:string){const $=cheerio.load(html);const body=$('body').text().replace(/\s+/g,' ');const name=$('h1').first().text().trim()||'Campeonato';const course=/\b25\s*m\b/.test(body)?'SCM':/\b50\s*m\b/.test(body)?'LCM':null;const date=parseDate(body);return{externalId:meetBase(url).split('/').pop()||meetBase(url),name,startDate:date,endDate:null,course:course as any,venue:null,city:null,officialUrl:meetBase(url)}}
function parseEntries(html:string,i:Identifier){const $=cheerio.load(html);const entries:ParsedEntry[]=[];$('body *').each((_,el)=>{const text=$(el).text().replace(/\s+/g,' ').trim();if(text.length<20||text.length>1600||!athleteMatch(text,i))return;const rx=/(?:\d{1,2}:\d{2}\s+)?((?:\d+x)?\d{2,4})\s*m?\s+(Livre|Costas|Peito|Borboleta|Medley)(?:.*?S[eé]rie\s*(\d+))?(?:.*?Raia\s*(\d+))?/gi;let m;while((m=rx.exec(text))){const eventLabel=`${m[1]} ${m[2]}`;if(entries.some(e=>normalize(e.eventLabel)===normalize(eventLabel)))continue;const after=text.slice(m.index,m.index+220);const seedMatch=after.match(/(?:balizamento|inscri[cç][aã]o|tempo)\s*[:\-]?\s*([0-9:'".,]+)/i);entries.push({eventLabel,seedTimeMs:seedMatch?parseSwimTime(seedMatch[1]):null,heat:m[3]?Number(m[3]):null,lane:m[4]?Number(m[4]):null,externalId:null})}});return entries}
function parsePage(html:string,url:string,label:string,i:Identifier,course:'SCM'|'LCM'|null,resultDate:string|null){const $=cheerio.load(html);const eventLabel=eventFrom(label)||eventFrom($('h1,h2,h3').text())||'';const found:ParsedResult[]=[];$('tr').each((_,tr)=>{const row=$(tr).text().replace(/\s+/g,' ').trim();if(!athleteMatch(row,i))return;const cells=$(tr).find('td').toArray().map(td=>$(td).text().replace(/\s+/g,' ').trim());const st=status(row);let timeMs:number|null=null;for(const c of [...cells].reverse()){const v=parseSwimTime(c);if(v!=null){timeMs=v;break}}if(timeMs==null&&!st)return;found.push({eventLabel,timeMs,status:st||'valid',externalId:null,sourceUrl:url,resultDate,course})});return found}
export const swimSystem:SourceAdapter={code:'swimsystem',async verifyIdentifier(identifier){const raw=identifier.metadata?.current_meet_url||identifier.metadata?.currentMeetUrl;if(!raw)return{ok:false,message:'URL do campeonato atual não informada'};let u:URL;try{u=new URL(raw)}catch{return{ok:false,message:'URL inválida'}};if(!/(^|\.)swimsystem\.app$/i.test(u.hostname))return{ok:false,message:'Fonte não pertence ao SwimSystem'};const base=meetBase(raw);const html=await get(base+'/athletes');const $=cheerio.load(html);const body=$('body').text().replace(/\s+/g,' ');if(!athleteMatch(body,identifier))return{ok:false,message:'Registro/nome não encontrado no campeonato informado'};const nameCandidate=$('body *').toArray().map(el=>$(el).text().replace(/\s+/g,' ').trim()).find(t=>t.length<180&&athleteMatch(t,identifier))||null;return{ok:true,externalName:nameCandidate}},async scanCurrent(identifier){const url=identifier.metadata?.current_meet_url||identifier.metadata?.currentMeetUrl;if(!url)return null;const base=meetBase(url);const html=await get(base);const meet=parseMeet(html,base);let entries:ParsedEntry[]=[];try{entries=parseEntries(await get(base+'/athletes'),identifier)}catch{}const pages=discover(html,base);const results:ParsedResult[]=[];for(const p of pages.slice(0,80)){try{results.push(...parsePage(await get(p.url),p.url,p.label,identifier,meet.course,meet.startDate))}catch{}}return{meet,entries,results}}}
